/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.border.EmptyBorder;

import forGraphics.Rectangle;
import forGraphics.Point;
import java.awt.Graphics2D;
//import forGraphics.Box;   //kutxa

/**
 *
 * @author arceredillo.adrian
 */
public class GraphExample extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrameMarrazkiak
     */
    public GraphExample() {
        initComponents();
        this.setResizable(false);
        JComboBoxFiguras.addItem("Puntua");
        JComboBoxFiguras.addItem("Laukizuzena");
        JComboBoxFiguras.addItem("Best Two");
        
        //JButtonLimpiar
        JButtonLimpiar.setBackground(new Color(0x9dce14));
        JButtonLimpiar.setBorder(new EmptyBorder(5, 15, 5, 15));
        
        /*
        g.drawLine(this.getWidth() / 2, 0, this.getWidth() / 2, this.getHeight());
        g.drawLine(0, this.getHeight() / 2, this.getWidth(), this.getHeight() / 2);
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextFieldAltuera = new javax.swing.JTextField();
        JLabelAltuera = new javax.swing.JLabel();
        JComboBoxFiguras = new javax.swing.JComboBox<>();
        JLabelElegirIrudia = new javax.swing.JLabel();
        JLabelGarbitu = new javax.swing.JLabel();
        JButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JTextFieldAltuera.setText("Altuera");

        JLabelAltuera.setText("Altuera");

        JComboBoxFiguras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxFigurasActionPerformed(evt);
            }
        });

        JLabelElegirIrudia.setText("Elegir figura: ");

        JLabelGarbitu.setText("Garbitu: ");

        JButtonLimpiar.setText("Clic!");
        JButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLabelGarbitu)
                    .addComponent(JLabelElegirIrudia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelAltuera)
                    .addComponent(JTextFieldAltuera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JButtonLimpiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(JComboBoxFiguras, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(JLabelAltuera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextFieldAltuera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboBoxFiguras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabelElegirIrudia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelGarbitu)
                    .addComponent(JButtonLimpiar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        Graphics g1 = this.getGraphics();
        
        g1.drawLine(50, 70, 50, this.getHeight() / 2);
        g1.drawLine(0, this.getHeight() / 2, this.getWidth(), this.getHeight() / 2);
        
        /*
        g1.drawLine(this.getWidth() / 2, 0, this.getWidth() / 2, this.getHeight());
        g1.drawLine(0, this.getHeight() / 2, this.getWidth(), this.getHeight() / 2);
        */
        
        int coordX = evt.getX();
        int coordY = evt.getY();
        //int altura = Integer.parseInt(JTextFieldAltuera.getText());
        //Kutxa k1 = new Kutxa(new Puntua(coordX, coordY),new Puntua(coordX + 100, coordY - 40), altura);
        
        Rectangle rec1 = new Rectangle(new Point(coordX, coordY),new Point(coordX + 100,coordY - 40));
        Point p1 = new Point(coordX, coordY);
        
        Graphics g = this.getGraphics();
        //k1.marraztu(g);
        //rec1.marraztu(g);
        //p1.marraztu(g);
        
        
        if (JComboBoxFiguras.getSelectedIndex() == 0) {
            p1.drawTest(g);
        } else if (JComboBoxFiguras.getSelectedIndex() == 1) {
            rec1.drawTest(g);
        } 
        
    }//GEN-LAST:event_formMouseClicked

    private void JComboBoxFigurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxFigurasActionPerformed
        // TODO add your handling code here:
        if (JComboBoxFiguras.getSelectedIndex() == 2) {
            JTextFieldAltuera.setEditable(true);
            JTextFieldAltuera.setEnabled(true);
            JTextFieldAltuera.setText("");
        } else {
            JTextFieldAltuera.setEditable(false);
            JTextFieldAltuera.setEnabled(false);
        }
        
    }//GEN-LAST:event_JComboBoxFigurasActionPerformed

    private void JButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonLimpiarActionPerformed
        // TODO add your handling code here:
        repaint();
    }//GEN-LAST:event_JButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphExample().setVisible(true);
                JTextFieldAltuera.setText("Sartu balio bat: ");
                JTextFieldAltuera.setEditable(false);
                JTextFieldAltuera.setEnabled(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JButtonLimpiar;
    public static javax.swing.JComboBox<String> JComboBoxFiguras;
    public static javax.swing.JLabel JLabelAltuera;
    public static javax.swing.JLabel JLabelElegirIrudia;
    public static javax.swing.JLabel JLabelGarbitu;
    public static javax.swing.JTextField JTextFieldAltuera;
    // End of variables declaration//GEN-END:variables
}
