/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc;

import myClasses.*;
import javax.swing.JOptionPane;

/**
 *
 * @author AdriAlex
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form BocetoGUI_start
     */
    public View() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Primera prueba GUI");
        
        JComboBoxTxostenak.addItem("...");
        JComboBoxTxostenak.addItem("Today's occupation");
        JComboBoxTxostenak.addItem("Underage customers");
        JComboBoxTxostenak.addItem("Desired customer's purchases");
        JComboBoxTxostenak.addItem("Morning / afternoon");
        JComboBoxTxostenak.addItem("Best sellers");
        JComboBoxTxostenak.addItem("The three least frequent customers");
        
        JSpinnerCustomerId.setValue(0);
        JSpinnerCustomerId.setEnabled(false);
        JTextAreaTxostenak.setAutoscrolls(true);
        JTextAreaTxostenak.setEditable(false);
        
        JTextFieldTodaysDate.setText("yyyy-mm-dd");
        JTextFieldTodaysDate.setEditable(false);
        JTextFieldTodaysDate.setEnabled(false);
        
        
        JFrameTextReports.setResizable(false);
        JTextFieldUsernameUser.setEditable(false);
        JTextFieldUsernameUser.setEnabled(false);
        //JFrameTextualReports.setSize(600, 600);
    }
    
    public static View visualizarGUI() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
                
            }
        });
        return v;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameTextReports = new javax.swing.JFrame();
        JComboBoxTxostenak = new javax.swing.JComboBox<>();
        JButtonPrintTxosten = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTextAreaTxostenak = new javax.swing.JTextArea();
        JButtonReturnStart = new javax.swing.JButton();
        JLabelSpecifyId = new javax.swing.JLabel();
        JSpinnerCustomerId = new javax.swing.JSpinner();
        JLabelSpecifyDate = new javax.swing.JLabel();
        JLabelTitulo1 = new javax.swing.JLabel();
        JTextFieldTodaysDate = new javax.swing.JTextField();
        JLabelIntro1 = new javax.swing.JLabel();
        JButtonSaveInFile = new javax.swing.JButton();
        JLabelUsername = new javax.swing.JLabel();
        JTextFieldUsernameUser = new javax.swing.JTextField();
        JLabelDateFormat = new javax.swing.JLabel();
        JFrameGraphicalReports = new javax.swing.JFrame();
        JCheckPurchaseHistory = new javax.swing.JCheckBox();
        JCheckBoxSortAge = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        JButtonViewGra = new javax.swing.JButton();
        JButtonGoBack = new javax.swing.JButton();
        JButtonClean = new javax.swing.JButton();
        JLabelGarageTitulo = new javax.swing.JLabel();
        JLabelGraphIntro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaGraphics = new javax.swing.JTextArea();
        JCheckBoxPurchaseEvolution = new javax.swing.JCheckBox();
        JDialogTextualUnderage = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JLabelTitulo = new javax.swing.JLabel();
        JLabelIntro = new javax.swing.JLabel();
        JButtonGoTxostenak = new javax.swing.JButton();
        JButtonGoGraphicall = new javax.swing.JButton();
        JButtonGoManage = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        JButtonProbarDBConection = new javax.swing.JButton();

        JComboBoxTxostenak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxTxostenakActionPerformed(evt);
            }
        });

        JButtonPrintTxosten.setText("View");
        JButtonPrintTxosten.setActionCommand("View Txostena");

        JTextAreaTxostenak.setColumns(20);
        JTextAreaTxostenak.setLineWrap(true);
        JTextAreaTxostenak.setRows(5);
        jScrollPane3.setViewportView(JTextAreaTxostenak);

        JButtonReturnStart.setText("Go back");

        JLabelSpecifyId.setText("Specify ID:");

        JLabelSpecifyDate.setText("Enter date:");

        JLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        JLabelTitulo1.setText("Garage HALAB");

        JLabelIntro1.setText("Welcome to Garage HALAB's official GUI.");

        JButtonSaveInFile.setText("Save");

        JLabelUsername.setText("Username:");

        JLabelDateFormat.setText("(yyyy-mm-dd)");

        javax.swing.GroupLayout JFrameTextReportsLayout = new javax.swing.GroupLayout(JFrameTextReports.getContentPane());
        JFrameTextReports.getContentPane().setLayout(JFrameTextReportsLayout);
        JFrameTextReportsLayout.setHorizontalGroup(
            JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JComboBoxTxostenak, 0, 228, Short.MAX_VALUE)
                                    .addComponent(JLabelIntro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(JButtonPrintTxosten, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JButtonReturnStart)))
                        .addGap(18, 18, 18)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(JLabelSpecifyDate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLabelSpecifyId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabelUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JSpinnerCustomerId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JButtonSaveInFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                            .addComponent(JLabelDateFormat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTextFieldUsernameUser)
                            .addComponent(JTextFieldTodaysDate))
                        .addGap(74, 74, 74))
                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                        .addComponent(JLabelTitulo1)
                        .addGap(66, 66, 66))))
        );
        JFrameTextReportsLayout.setVerticalGroup(
            JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrameTextReportsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JLabelTitulo1)
                .addGap(12, 12, 12)
                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelIntro1)
                    .addComponent(JLabelSpecifyId))
                .addGap(18, 18, 18)
                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboBoxTxostenak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonReturnStart)
                    .addComponent(JButtonPrintTxosten)
                    .addComponent(JSpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                        .addComponent(JLabelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextFieldUsernameUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JLabelSpecifyDate)
                        .addGap(5, 5, 5)
                        .addComponent(JLabelDateFormat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTextFieldTodaysDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonSaveInFile, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addGap(33, 33, 33))
        );

        JCheckPurchaseHistory.setText("Certain customer's purchase history");

        JCheckBoxSortAge.setText("Sort by age");

        JButtonViewGra.setText("View");
        JButtonViewGra.setActionCommand("View Graphics");

        JButtonGoBack.setText("Go back");
        JButtonGoBack.setActionCommand("Go back to start");

        JButtonClean.setText("Clean");

        JLabelGarageTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelGarageTitulo.setText("Garage HALAB");

        JLabelGraphIntro.setText("This section allows you to know more about the garage.");

        JTextAreaGraphics.setColumns(20);
        JTextAreaGraphics.setRows(5);
        jScrollPane1.setViewportView(JTextAreaGraphics);

        JCheckBoxPurchaseEvolution.setText("Purchase evolution");

        javax.swing.GroupLayout JFrameGraphicalReportsLayout = new javax.swing.GroupLayout(JFrameGraphicalReports.getContentPane());
        JFrameGraphicalReports.getContentPane().setLayout(JFrameGraphicalReportsLayout);
        JFrameGraphicalReportsLayout.setHorizontalGroup(
            JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrameGraphicalReportsLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelGarageTitulo)
                    .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrameGraphicalReportsLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JCheckBoxPurchaseEvolution)
                                .addComponent(JCheckPurchaseHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCheckBoxSortAge)
                                .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                                    .addComponent(JButtonViewGra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(JButtonClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(JButtonGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(49, 49, 49))
                        .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                            .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabelGraphIntro))
                            .addContainerGap()))))
        );
        JFrameGraphicalReportsLayout.setVerticalGroup(
            JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(JLabelGarageTitulo)
                .addGap(18, 18, 18)
                .addComponent(JLabelGraphIntro)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                        .addComponent(JCheckBoxPurchaseEvolution)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCheckPurchaseHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JCheckBoxSortAge)
                        .addGap(18, 18, 18)
                        .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtonViewGra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JButtonClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButtonGoBack))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout JDialogTextualUnderageLayout = new javax.swing.GroupLayout(JDialogTextualUnderage.getContentPane());
        JDialogTextualUnderage.getContentPane().setLayout(JDialogTextualUnderageLayout);
        JDialogTextualUnderageLayout.setHorizontalGroup(
            JDialogTextualUnderageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTextualUnderageLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        JDialogTextualUnderageLayout.setVerticalGroup(
            JDialogTextualUnderageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTextualUnderageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        JLabelTitulo.setText("Garage HALAB");

        JLabelIntro.setText("Welcome to Garage HALAB's official GUI.");

        JButtonGoTxostenak.setText("Textual Reports");

        JButtonGoGraphicall.setText("Graphicall Reports");

        JButtonGoManage.setText("Manage Garage");

        JButtonProbarDBConection.setText("Probar DB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JButtonGoTxostenak, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonGoGraphicall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(JLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(JLabelIntro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(JButtonGoManage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButtonProbarDBConection)
                .addGap(197, 197, 197))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(JLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelIntro)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonGoTxostenak)
                    .addComponent(JButtonGoGraphicall))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(JButtonGoManage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonProbarDBConection)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxTxostenakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxTxostenakActionPerformed
        // TODO add your handling code here:
        JTextAreaTxostenak.setText("Waiting for a report request...");

        if (JComboBoxTxostenak.getSelectedIndex() == 0) {
            System.out.println("Actual report: No report selected. Please, choose one and press the 'View' button. \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 1) {

            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString());
            System.out.println("\t-> Introduce una fecha para ver las reservas existentes. \n");
            JTextFieldTodaysDate.setEditable(true);
            JTextFieldTodaysDate.setEnabled(true);
            JSpinnerCustomerId.setEnabled(false);
            JTextFieldUsernameUser.setEnabled(false);
            JTextFieldTodaysDate.setText("");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 2) {
            JSpinnerCustomerId.setEnabled(false);
            JTextFieldTodaysDate.setEnabled(false);
            JTextFieldUsernameUser.setEnabled(false);
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString());
            System.out.println("\t-> A continuación, podrás ver las compras que ha realizado un cliente determinado. Para ello, ingresa el id de dicho cliente. \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 3) {
            JTextFieldUsernameUser.setText("");
            JSpinnerCustomerId.setValue(0);
            JSpinnerCustomerId.setEnabled(true);
            JTextFieldTodaysDate.setEnabled(false);
            JTextFieldUsernameUser.setEditable(true);
            JTextFieldUsernameUser.setEnabled(true);
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString());
            System.out.println("\t-> A continuación, podrás ver las compras que ha realizado un cliente determinado. Para ello, ingresa el id de dicho cliente. \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 4) {
            JTextFieldUsernameUser.setText("");
            JSpinnerCustomerId.setValue(0);
            JSpinnerCustomerId.setEnabled(true);
            JTextFieldTodaysDate.setEnabled(false);
            JTextFieldUsernameUser.setEditable(true);
            JTextFieldUsernameUser.setEnabled(true);
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString());
            System.out.println("\t-> A continuación, podrás ver las compras que ha realizado un cliente determinado. Para ello, ingresa el id de dicho cliente. \n");

        } else {
            System.out.println("Choose any option from the combo box and press 'View'. \n");
            JTextFieldTodaysDate.setEditable(false);
            JTextFieldTodaysDate.setEnabled(false);
            JSpinnerCustomerId.setEnabled(false);
            JTextFieldUsernameUser.setEditable(false);
            JTextFieldUsernameUser.setEnabled(false);
        }

    }//GEN-LAST:event_JComboBoxTxostenakActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton JButtonClean;
    public static javax.swing.JButton JButtonGoBack;
    public static javax.swing.JButton JButtonGoGraphicall;
    public static javax.swing.JButton JButtonGoManage;
    public static javax.swing.JButton JButtonGoTxostenak;
    public static javax.swing.JButton JButtonPrintTxosten;
    public static javax.swing.JButton JButtonProbarDBConection;
    public static javax.swing.JButton JButtonReturnStart;
    public static javax.swing.JButton JButtonSaveInFile;
    public static javax.swing.JButton JButtonViewGra;
    public static javax.swing.JCheckBox JCheckBoxPurchaseEvolution;
    public static javax.swing.JCheckBox JCheckBoxSortAge;
    public static javax.swing.JCheckBox JCheckPurchaseHistory;
    public static javax.swing.JComboBox<String> JComboBoxTxostenak;
    private javax.swing.JDialog JDialogTextualUnderage;
    public static javax.swing.JFrame JFrameGraphicalReports;
    public static javax.swing.JFrame JFrameTextReports;
    public static javax.swing.JLabel JLabelDateFormat;
    public static javax.swing.JLabel JLabelGarageTitulo;
    public static javax.swing.JLabel JLabelGraphIntro;
    public static javax.swing.JLabel JLabelIntro;
    public static javax.swing.JLabel JLabelIntro1;
    public static javax.swing.JLabel JLabelSpecifyDate;
    public static javax.swing.JLabel JLabelSpecifyId;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JLabel JLabelTitulo1;
    public static javax.swing.JLabel JLabelUsername;
    public static javax.swing.JSpinner JSpinnerCustomerId;
    public static javax.swing.JTextArea JTextAreaGraphics;
    public static javax.swing.JTextArea JTextAreaTxostenak;
    public static javax.swing.JTextField JTextFieldTodaysDate;
    public static javax.swing.JTextField JTextFieldUsernameUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}


