/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc;

import myClasses.*;
import javax.swing.*;


import java.awt.*;
import java.awt.event.*;
import java.awt.Graphics;

/**
 *
 * @author AdriAlex
 */
public class View extends javax.swing.JFrame {

    FondoPanel fondo = new FondoPanel();
    
    public View() {
        
        this.setContentPane(fondo);
        
        
        initComponents();
        //this.setResizable(false);
        this.setSize(900, 500);
        this.setResizable(false);
        this.setTitle("Primera prueba GUI");
        
        
        
        
        
        
        JComboBoxTxostenak.addItem("...");
        JComboBoxTxostenak.addItem("Monthly occupation");
        JComboBoxTxostenak.addItem("Underage customers");
        JComboBoxTxostenak.addItem("Desired customer's purchases");
        JComboBoxTxostenak.addItem("Morning / afternoon");
        JComboBoxTxostenak.addItem("Best sellers");
        JComboBoxTxostenak.addItem("The three least frequent customers");
        
        
        //Choose customer using "choice" tool
        ChoiceCustomer.setEnabled(false);
        ChoiceCustomer.addItem("...");        
        for (int i = 0; i < Model.getAllCustomers().size(); ++i) {
            ChoiceCustomer.addItem(Model.getAllCustomers().get(i).getUsername());
        }
        
        
        JSpinnerCustomerId.setValue(0);
        JSpinnerCustomerId.setEnabled(false);
        JTextAreaTxostenak.setAutoscrolls(true);
        JTextAreaTxostenak.setEditable(false);
        
        JTextFieldTodaysDate.setText("yyyy-mm-dd");
        JTextFieldTodaysDate.setEditable(false);
        JTextFieldTodaysDate.setEnabled(false);
        
        JFrameTextReports.setResizable(false);
        
        
        //Textual Reports - Worker's section - Process to be allowed to save data on files
        JButtonLogOut.setEnabled(false);
        JButtonValidateWorker.setEnabled(false);
        
        JTextFieldWorkerNameUser.setEnabled(false); JTextFieldWorkerNameUser.setEditable(false);
        JTextFieldWorkerSurnameUser.setEnabled(false);  JTextFieldWorkerSurnameUser.setEditable(false);
        JPasswordFieldPasswordUser.setEnabled(false);   JPasswordFieldPasswordUser.setEditable(false);
        
        JTextAreaSaveProcessInstructor.setEnabled(false);   JTextAreaSaveProcessInstructor.setEditable(false);
        JTextAreaSaveProcessInstructor.setAutoscrolls(true);
        
        JButtonSaveUsersFile.setEnabled(false);
        JButtonSaveCatalog.setEnabled(false);
        JButtonSaveEntireStaff.setEnabled(false);
        JButtonSaveCabin.setEnabled(false);
        
        JButtonViewGraph.setEnabled(false);        
        JButtonClean.setEnabled(false);
        
        JCheckBoxViewGraphicOnTable.setEnabled(false);
        
        
        
        
        
        
    }
    
    
    
    public static View visualizarGUI() {
        View v = new View();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                v.setVisible(true);
                
            }
        });
        return v;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFrameTextReports = new javax.swing.JFrame();
        JComboBoxTxostenak = new javax.swing.JComboBox<>();
        JButtonPrintTxosten = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTextAreaTxostenak = new javax.swing.JTextArea();
        JButtonReturnStart = new javax.swing.JButton();
        JLabelSpecifyId = new javax.swing.JLabel();
        JSpinnerCustomerId = new javax.swing.JSpinner();
        JLabelSpecifyDate = new javax.swing.JLabel();
        JLabelTitulo1 = new javax.swing.JLabel();
        JTextFieldTodaysDate = new javax.swing.JTextField();
        JLabelIntro1 = new javax.swing.JLabel();
        CheckboxViewOnTable = new java.awt.Checkbox();
        ChoiceCustomer = new java.awt.Choice();
        JLabelChooseCustomer = new javax.swing.JLabel();
        JButtonClear = new javax.swing.JButton();
        JButtonSaveUsersFile = new javax.swing.JButton();
        JButtonSaveCatalog = new javax.swing.JButton();
        JButtonLoginToSave = new javax.swing.JButton();
        JLabelWorkerName = new javax.swing.JLabel();
        JTextFieldWorkerNameUser = new javax.swing.JTextField();
        JLabelWorkerSurname = new javax.swing.JLabel();
        JTextFieldWorkerSurnameUser = new javax.swing.JTextField();
        JLabelWorkerPassword = new javax.swing.JLabel();
        JPasswordFieldPasswordUser = new javax.swing.JPasswordField();
        JButtonValidateWorker = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        JLabelStaffOnly = new javax.swing.JLabel();
        JButtonSaveEntireStaff = new javax.swing.JButton();
        JButtonSaveCabin = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTextAreaSaveProcessInstructor = new javax.swing.JTextArea();
        JButtonLogOut = new javax.swing.JButton();
        JFrameGraphicalReports = new javax.swing.JFrame();
        JCheckBoxSortAge = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        JButtonStartGra = new javax.swing.JButton();
        JButtonGoBack = new javax.swing.JButton();
        JButtonClean = new javax.swing.JButton();
        JLabelGarageTitulo = new javax.swing.JLabel();
        JLabelGraphIntro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTextAreaGraphics = new javax.swing.JTextArea();
        JCheckBoxMonthlyOccupancy = new javax.swing.JCheckBox();
        JCheckBoxBestTwoCustomers = new javax.swing.JCheckBox();
        JButtonViewGraph = new javax.swing.JButton();
        JCheckBoxViewGraphicOnTable = new javax.swing.JCheckBox();
        JDialogTextual = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableDataOnTable = new javax.swing.JTable();
        JButtonReturnFromTable = new javax.swing.JButton();
        JFrameAdminSection = new javax.swing.JFrame();
        ButtonGroupGraphReports = new javax.swing.ButtonGroup();
        JDialogGraphicReports = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTableGraphicInfo = new javax.swing.JTable();
        JButtonReturnToGraphic = new javax.swing.JButton();
        JLabelTitulo = new javax.swing.JLabel();
        JLabelIntro = new javax.swing.JLabel();
        JButtonGoTxostenak = new javax.swing.JButton();
        JButtonGoGraphicall = new javax.swing.JButton();
        JButtonVisitWebsite = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        JFrameTextReports.setResizable(false);

        JComboBoxTxostenak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxTxostenakActionPerformed(evt);
            }
        });

        JButtonPrintTxosten.setText("View");
        JButtonPrintTxosten.setActionCommand("View Txostena");

        JTextAreaTxostenak.setColumns(20);
        JTextAreaTxostenak.setLineWrap(true);
        JTextAreaTxostenak.setRows(5);
        jScrollPane3.setViewportView(JTextAreaTxostenak);

        JButtonReturnStart.setText("Go back");

        JLabelSpecifyId.setText("Specify ID:");

        JLabelSpecifyDate.setText("Date: (yyyy-mm-dd)");

        JLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelTitulo1.setForeground(new java.awt.Color(0, 0, 0));
        JLabelTitulo1.setText("Garage HALAB");

        JLabelIntro1.setText("Welcome to Garage HALAB's official GUI.");

        CheckboxViewOnTable.setLabel("Table");

        ChoiceCustomer.setName("MenuCustomers"); // NOI18N

        JLabelChooseCustomer.setText("Choose Customer:");

        JButtonClear.setText("Clear");

        JButtonSaveUsersFile.setText("Customer Registration");
        JButtonSaveUsersFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSaveUsersFileActionPerformed(evt);
            }
        });

        JButtonSaveCatalog.setText("Download Catalog");

        JButtonLoginToSave.setText("Login");

        JLabelWorkerName.setText("Name:");

        JLabelWorkerSurname.setText("Surname:");

        JLabelWorkerPassword.setText("Password:");

        JButtonValidateWorker.setText("Validate");

        JLabelStaffOnly.setText("Staff Only");

        JButtonSaveEntireStaff.setText("Entire Staff");

        JButtonSaveCabin.setText("Cabin Structure");

        JTextAreaSaveProcessInstructor.setColumns(20);
        JTextAreaSaveProcessInstructor.setLineWrap(true);
        JTextAreaSaveProcessInstructor.setRows(5);
        jScrollPane4.setViewportView(JTextAreaSaveProcessInstructor);

        JButtonLogOut.setText("Logout");

        javax.swing.GroupLayout JFrameTextReportsLayout = new javax.swing.GroupLayout(JFrameTextReports.getContentPane());
        JFrameTextReports.getContentPane().setLayout(JFrameTextReportsLayout);
        JFrameTextReportsLayout.setHorizontalGroup(
            JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLabelWorkerPassword)
                            .addComponent(JLabelWorkerSurname)
                            .addComponent(JLabelWorkerName))
                        .addGap(18, 18, 18)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addComponent(JTextFieldWorkerNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabelStaffOnly)
                                .addGap(94, 94, 94))
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                        .addComponent(JPasswordFieldPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JButtonValidateWorker))
                                    .addComponent(JTextFieldWorkerSurnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrameTextReportsLayout.createSequentialGroup()
                        .addComponent(JButtonSaveUsersFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonSaveCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonSaveEntireStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonSaveCabin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrameTextReportsLayout.createSequentialGroup()
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JComboBoxTxostenak, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLabelIntro1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                        .addComponent(JButtonPrintTxosten, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(JButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CheckboxViewOnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(JLabelTitulo1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLabelChooseCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChoiceCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addComponent(JLabelSpecifyId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JSpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JLabelSpecifyDate)
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addComponent(JButtonLoginToSave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JButtonReturnStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTextFieldTodaysDate)))
                    .addComponent(jSeparator4))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        JFrameTextReportsLayout.setVerticalGroup(
            JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JFrameTextReportsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JLabelTitulo1)
                .addGap(14, 14, 14)
                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                        .addComponent(JLabelIntro1)
                        .addGap(18, 18, 18)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JComboBoxTxostenak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonPrintTxosten)
                            .addComponent(JButtonClear)
                            .addComponent(JSpinnerCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelSpecifyId))
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                .addComponent(JLabelChooseCustomer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChoiceCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLabelSpecifyDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTextFieldTodaysDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JButtonLoginToSave)
                                    .addComponent(JButtonLogOut))
                                .addGap(20, 20, 20)
                                .addComponent(JButtonReturnStart))
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JLabelWorkerName)
                                .addComponent(JTextFieldWorkerNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JLabelStaffOnly))
                            .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                                    .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JLabelWorkerSurname)
                                        .addComponent(JTextFieldWorkerSurnameUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JPasswordFieldPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JLabelWorkerPassword)
                                        .addComponent(JButtonValidateWorker)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(JFrameTextReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtonSaveEntireStaff)
                            .addComponent(JButtonSaveCabin)
                            .addComponent(JButtonSaveCatalog)
                            .addComponent(JButtonSaveUsersFile))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(JFrameTextReportsLayout.createSequentialGroup()
                        .addComponent(CheckboxViewOnTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        JFrameGraphicalReports.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JCheckBoxSortAge.setText("Sort by age");

        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JButtonStartGra.setText("Start");
        JButtonStartGra.setActionCommand("Start Graphics");
        JButtonStartGra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        JButtonGoBack.setText("Go back");
        JButtonGoBack.setActionCommand("Go back to start");

        JButtonClean.setText("Clean");

        JLabelGarageTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelGarageTitulo.setText("Garage HALAB");

        JLabelGraphIntro.setText("This section allows you to know more about the garage.");

        JTextAreaGraphics.setEditable(false);
        JTextAreaGraphics.setColumns(20);
        JTextAreaGraphics.setLineWrap(true);
        JTextAreaGraphics.setRows(5);
        jScrollPane1.setViewportView(JTextAreaGraphics);

        JCheckBoxMonthlyOccupancy.setText("Monthly Occupancy");

        JCheckBoxBestTwoCustomers.setText("Best Two Customers");

        JButtonViewGraph.setText("View");
        JButtonViewGraph.setActionCommand("View Graphic");

        JCheckBoxViewGraphicOnTable.setText("Table");
        JCheckBoxViewGraphicOnTable.setActionCommand("GraphicOnTable");
        JCheckBoxViewGraphicOnTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JFrameGraphicalReportsLayout = new javax.swing.GroupLayout(JFrameGraphicalReports.getContentPane());
        JFrameGraphicalReports.getContentPane().setLayout(JFrameGraphicalReportsLayout);
        JFrameGraphicalReportsLayout.setHorizontalGroup(
            JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                        .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                                .addComponent(JCheckBoxBestTwoCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCheckBoxMonthlyOccupancy, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JCheckBoxSortAge)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JButtonGoBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                                .addComponent(JButtonViewGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JButtonStartGra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78))
                    .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                                .addComponent(JLabelGraphIntro)
                                .addGap(28, 28, 28)
                                .addComponent(JCheckBoxViewGraphicOnTable))
                            .addComponent(JLabelGarageTitulo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JFrameGraphicalReportsLayout.setVerticalGroup(
            JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(JLabelGarageTitulo)
                .addGap(18, 18, 18)
                .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelGraphIntro)
                    .addComponent(JCheckBoxViewGraphicOnTable))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JFrameGraphicalReportsLayout.createSequentialGroup()
                        .addComponent(JButtonStartGra)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonGoBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JButtonViewGraph)
                            .addComponent(JButtonClean)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCheckBoxSortAge)
                    .addGroup(JFrameGraphicalReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JCheckBoxBestTwoCustomers)
                        .addComponent(JCheckBoxMonthlyOccupancy)))
                .addContainerGap(306, Short.MAX_VALUE))
        );

        JTableDataOnTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        JTableDataOnTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(JTableDataOnTable);

        JButtonReturnFromTable.setText("Go back");
        JButtonReturnFromTable.setActionCommand("Return to textual reports");

        javax.swing.GroupLayout JDialogTextualLayout = new javax.swing.GroupLayout(JDialogTextual.getContentPane());
        JDialogTextual.getContentPane().setLayout(JDialogTextualLayout);
        JDialogTextualLayout.setHorizontalGroup(
            JDialogTextualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTextualLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(JDialogTextualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(JButtonReturnFromTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        JDialogTextualLayout.setVerticalGroup(
            JDialogTextualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogTextualLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JButtonReturnFromTable)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JFrameAdminSectionLayout = new javax.swing.GroupLayout(JFrameAdminSection.getContentPane());
        JFrameAdminSection.getContentPane().setLayout(JFrameAdminSectionLayout);
        JFrameAdminSectionLayout.setHorizontalGroup(
            JFrameAdminSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JFrameAdminSectionLayout.setVerticalGroup(
            JFrameAdminSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        JTableGraphicInfo.setBackground(new java.awt.Color(255, 153, 153));
        JTableGraphicInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        JTableGraphicInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane6.setViewportView(JTableGraphicInfo);

        JButtonReturnToGraphic.setText("Go Back");
        JButtonReturnToGraphic.setActionCommand("Return To Graphic Section");

        javax.swing.GroupLayout JDialogGraphicReportsLayout = new javax.swing.GroupLayout(JDialogGraphicReports.getContentPane());
        JDialogGraphicReports.getContentPane().setLayout(JDialogGraphicReportsLayout);
        JDialogGraphicReportsLayout.setHorizontalGroup(
            JDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogGraphicReportsLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(JDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                    .addComponent(JButtonReturnToGraphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
        );
        JDialogGraphicReportsLayout.setVerticalGroup(
            JDialogGraphicReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialogGraphicReportsLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(JButtonReturnToGraphic)
                .addGap(103, 103, 103))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelTitulo.setText("Welcome, driver!");

        JLabelIntro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        JLabelIntro.setForeground(new java.awt.Color(255, 255, 255));
        JLabelIntro.setText("You're in HALAB Garage's official GUI.");

        JButtonGoTxostenak.setText("Textual Reports");

        JButtonGoGraphicall.setText("Graphicall Reports");

        JButtonVisitWebsite.setText("More...");
        JButtonVisitWebsite.setActionCommand("Visit Website");
        JButtonVisitWebsite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonVisitWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonGoGraphicall, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JLabelTitulo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JButtonGoTxostenak, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabelIntro))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonGoTxostenak)
                    .addComponent(JLabelIntro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonGoGraphicall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JButtonVisitWebsite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLabelTitulo)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonSaveUsersFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSaveUsersFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSaveUsersFileActionPerformed

    private void JComboBoxTxostenakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxTxostenakActionPerformed
        // TODO add your handling code here:

        //JTextAreaTxostenak.setText("Waiting for a report request...");

        if (JComboBoxTxostenak.getSelectedIndex() == 0) {
            System.out.println("Actual report: No report selected. Please, choose one and press the 'View' button. \n");
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(false);  CheckboxViewOnTable.setState(false);
            

        } else if (JComboBoxTxostenak.getSelectedIndex() == 1) {
            
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(true);   CheckboxViewOnTable.setState(false);
            
            JTextFieldTodaysDate.setEditable(true); JTextFieldTodaysDate.setEnabled(true);
            JSpinnerCustomerId.setEnabled(false);
            ChoiceCustomer.setEnabled(false);
            JTextFieldTodaysDate.setText("");
            
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString() + ". \n");
            
        } else if (JComboBoxTxostenak.getSelectedIndex() == 2) {
            
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(true);   CheckboxViewOnTable.setState(false);
            
            JSpinnerCustomerId.setEnabled(false);
            JTextFieldTodaysDate.setEnabled(false);
            ChoiceCustomer.setEnabled(false);

            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString() + ". \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 3) {
            
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(true);   CheckboxViewOnTable.setState(false);
            
            JTextFieldTodaysDate.setEnabled(false);
            ChoiceCustomer.setEnabled(true);
            JSpinnerCustomerId.setValue(0); JSpinnerCustomerId.setEnabled(false);
            
            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString() + ". \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 4) {
            
            //CheckboxViewOnTable.setEnabled(false);  //disable the option of viewing on a table the data/result of this report (morning and afternoon reservations)
            
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(false);   CheckboxViewOnTable.setState(false);
            
            JSpinnerCustomerId.setValue(0); JSpinnerCustomerId.setEnabled(true);
            JTextFieldTodaysDate.setEnabled(false);
            ChoiceCustomer.setEnabled(false);

            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString() + ". \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 5) {
            
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(true);   CheckboxViewOnTable.setState(false);
            
            JSpinnerCustomerId.setValue(0); JSpinnerCustomerId.setEnabled(false);
            JTextFieldTodaysDate.setEnabled(false);
            ChoiceCustomer.setEnabled(false);

            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString() + ". \n");

        } else if (JComboBoxTxostenak.getSelectedIndex() == 6) {
            
            CheckboxViewOnTable.setVisible(true);   CheckboxViewOnTable.setEnabled(true);   CheckboxViewOnTable.setState(false);
            
            JSpinnerCustomerId.setValue(0); JSpinnerCustomerId.setEnabled(false);
            JTextFieldTodaysDate.setEnabled(false);
            ChoiceCustomer.setEnabled(false);

            System.out.println("Actual report: " + JComboBoxTxostenak.getSelectedItem().toString() + ". \n");

        }
        
        else {
            System.out.println("Choose any option from the combo box and press 'View'. \n");
            
            //CheckboxViewOnTable.setEnabled(true);
            
            JTextFieldTodaysDate.setEditable(false);    JTextFieldTodaysDate.setEnabled(false);
            JSpinnerCustomerId.setEnabled(false);
            ChoiceCustomer.setEnabled(false);

        } 
        
        
        //########################################################
        
        
        
        
    }//GEN-LAST:event_JComboBoxTxostenakActionPerformed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new View().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup ButtonGroupGraphReports;
    public static java.awt.Checkbox CheckboxViewOnTable;
    public static java.awt.Choice ChoiceCustomer;
    public static javax.swing.JButton JButtonClean;
    public static javax.swing.JButton JButtonClear;
    public static javax.swing.JButton JButtonGoBack;
    public static javax.swing.JButton JButtonGoGraphicall;
    public static javax.swing.JButton JButtonGoTxostenak;
    public static javax.swing.JButton JButtonLogOut;
    public static javax.swing.JButton JButtonLoginToSave;
    public static javax.swing.JButton JButtonPrintTxosten;
    public static javax.swing.JButton JButtonReturnFromTable;
    public static javax.swing.JButton JButtonReturnStart;
    public static javax.swing.JButton JButtonReturnToGraphic;
    public static javax.swing.JButton JButtonSaveCabin;
    public static javax.swing.JButton JButtonSaveCatalog;
    public static javax.swing.JButton JButtonSaveEntireStaff;
    public static javax.swing.JButton JButtonSaveUsersFile;
    public static javax.swing.JButton JButtonStartGra;
    public static javax.swing.JButton JButtonValidateWorker;
    public static javax.swing.JButton JButtonViewGraph;
    public static javax.swing.JButton JButtonVisitWebsite;
    public static javax.swing.JCheckBox JCheckBoxBestTwoCustomers;
    public static javax.swing.JCheckBox JCheckBoxMonthlyOccupancy;
    public static javax.swing.JCheckBox JCheckBoxSortAge;
    public static javax.swing.JCheckBox JCheckBoxViewGraphicOnTable;
    public static javax.swing.JComboBox<String> JComboBoxTxostenak;
    public static javax.swing.JDialog JDialogGraphicReports;
    public static javax.swing.JDialog JDialogTextual;
    public static javax.swing.JFrame JFrameAdminSection;
    public static javax.swing.JFrame JFrameGraphicalReports;
    public static javax.swing.JFrame JFrameTextReports;
    public static javax.swing.JLabel JLabelChooseCustomer;
    public static javax.swing.JLabel JLabelGarageTitulo;
    public static javax.swing.JLabel JLabelGraphIntro;
    public static javax.swing.JLabel JLabelIntro;
    public static javax.swing.JLabel JLabelIntro1;
    public static javax.swing.JLabel JLabelSpecifyDate;
    public static javax.swing.JLabel JLabelSpecifyId;
    public static javax.swing.JLabel JLabelStaffOnly;
    public static javax.swing.JLabel JLabelTitulo;
    public static javax.swing.JLabel JLabelTitulo1;
    public static javax.swing.JLabel JLabelWorkerName;
    public static javax.swing.JLabel JLabelWorkerPassword;
    public static javax.swing.JLabel JLabelWorkerSurname;
    public static javax.swing.JPasswordField JPasswordFieldPasswordUser;
    public static javax.swing.JSpinner JSpinnerCustomerId;
    javax.swing.JTable JTableDataOnTable;
    public static javax.swing.JTable JTableGraphicInfo;
    public static javax.swing.JTextArea JTextAreaGraphics;
    public static javax.swing.JTextArea JTextAreaSaveProcessInstructor;
    public static javax.swing.JTextArea JTextAreaTxostenak;
    public static javax.swing.JTextField JTextFieldTodaysDate;
    public static javax.swing.JTextField JTextFieldWorkerNameUser;
    public static javax.swing.JTextField JTextFieldWorkerSurnameUser;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
    
    
    
    class FondoPanel extends JPanel {
        private Image imagen;
        
        @Override
        public void paint(Graphics g) {
            //JFrameTextReports.getContentPane().setBackground(new Color(64,93,97));
            //JFrameTextReports.getContentPane().setBackground(new Color(149,3,14));
            
            //imagen = new ImageIcon(getClass().getResource("/images/fondoF1_1.jpg")).getImage();
            //imagen = new ImageIcon(getClass().getResource("/images/animated3.gif")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
            
        }
    }
    
    /*
    public void paint2(Graphics draw) {
    //esto solamente lo utilizaré para darle un nuevo color de fondo al jframe
        JFrameTextReports.getContentPane().setBackground(new Color(70, 80, 70));
    }
    */

    
}


